name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Push to GitLab
        env:
          GITLAB_URL: ${{ secrets.GITLAB_URL }}
          GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

          # GitLab 远程仓库 URL（使用 Token 进行认证）
          GITLAB_REMOTE="https://oauth2:${GITLAB_TOKEN}@${GITLAB_URL}/${GITLAB_REPO}"

          # 添加 GitLab 远程仓库
          git remote add gitlab "$GITLAB_REMOTE" || git remote set-url gitlab "$GITLAB_REMOTE"

          # 先拉取 GitLab 最新代码并合并
          git fetch gitlab main
          git merge --no-edit gitlab/main || git rebase gitlab/main

          # 推送到 GitLab
          git push gitlab main
